#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-chronic_duration
Version  : 0.10.6
Release  : 7
URL      : https://rubygems.org/downloads/chronic_duration-0.10.6.gem
Source0  : https://rubygems.org/downloads/chronic_duration-0.10.6.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core

%description
[![Build Status](https://travis-ci.org/hpoydar/chronic_duration.png?branch=master)](https://travis-ci.org/hpoydar/chronic_duration)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n chronic_duration-0.10.6
gem spec %{SOURCE0} -l --ruby > rubygem-chronic_duration.gemspec

%build
gem build rubygem-chronic_duration.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
chronic_duration-0.10.6.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/chronic_duration-0.10.6.gem
/usr/lib64/ruby/gems/2.3.0/gems/chronic_duration-0.10.6/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/chronic_duration-0.10.6/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/chronic_duration-0.10.6/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/chronic_duration-0.10.6/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/chronic_duration-0.10.6/README.md
/usr/lib64/ruby/gems/2.3.0/gems/chronic_duration-0.10.6/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/chronic_duration-0.10.6/chronic_duration.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/chronic_duration-0.10.6/lib/chronic_duration.rb
/usr/lib64/ruby/gems/2.3.0/gems/chronic_duration-0.10.6/lib/chronic_duration/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/chronic_duration-0.10.6/spec/lib/chronic_duration_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/chronic_duration-0.10.6/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/specifications/chronic_duration-0.10.6.gemspec
